export class Cosignature {
    /**
    * The hash of parent aggregate transaction that has been signed by a cosignatory of the transaction.
    */
    'parentHash'?: string;
    /**
    * The signatures generated by signing the parent aggregate transaction hash.
    */
    'signature'?: string;
    /**
    * The signer of the transaction.
    */
    'signer'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "parentHash",
            "baseName": "parentHash",
            "type": "string"
        },
        {
            "name": "signature",
            "baseName": "signature",
            "type": "string"
        },
        {
            "name": "signer",
            "baseName": "signer",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Cosignature.attributeTypeMap;
    }
}

