export * from './accountRoutesApi';
import { AccountRoutesApi } from './accountRoutesApi';
export * from './blockRoutesApi';
import { BlockRoutesApi } from './blockRoutesApi';
export * from './chainRoutesApi';
import { ChainRoutesApi } from './chainRoutesApi';
export * from './diagnosticRoutesApi';
import { DiagnosticRoutesApi } from './diagnosticRoutesApi';
export * from './mosaicRoutesApi';
import { MosaicRoutesApi } from './mosaicRoutesApi';
export * from './namespaceRoutesApi';
import { NamespaceRoutesApi } from './namespaceRoutesApi';
export * from './networkRoutesApi';
import { NetworkRoutesApi } from './networkRoutesApi';
export * from './nodeRoutesApi';
import { NodeRoutesApi } from './nodeRoutesApi';
export * from './transactionRoutesApi';
import { TransactionRoutesApi } from './transactionRoutesApi';
export const APIS = [AccountRoutesApi, BlockRoutesApi, ChainRoutesApi, DiagnosticRoutesApi, MosaicRoutesApi, NamespaceRoutesApi, NetworkRoutesApi, NodeRoutesApi, TransactionRoutesApi];
