

/**
 * Co-signature signed transaction.
 */
export class CosignatureSignedTransaction {
    /**
     * @param parentHash
     * @param signature
     * @param signer
     */
    constructor(
                /**
                 * The hash of parent aggregate transaction that has been signed by a cosignatory of the transaction
                 */
                public readonly parentHash: string,
                /**
                 * The signatures generated by signing the parent aggregate transaction hash.
                 */
                public readonly signature: string,
                /**
                 * The signer of the transaction.
                 */
                public readonly signer: string) {}
}
